version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: XenovaGamings-Server/Dockerfile
    container_name: xenova-api
    ports:
      - "5000:8080"
    depends_on:
      - db
      - service

  service:
    build:
      context: .
      dockerfile: XenovaGamings-Service/Dockerfile
    container_name: xenova-service
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: xenova-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: xenova_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
